language: java
jdk:
  - openjdk8

# Travis CI가 어느 브랜치가 푸시될 때 수행할지 설정한다.
branches:
  only:
    - master

# 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시한다. 그 후 다음 배포 때부터
# 의존성이 같다면 다시 내려받지 않도록 설정한다.
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# master 브랜치에 푸시되었을 때 수행하는 명령
# gradlew를 통해 clean & buile를 수행한다.
script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람이 오도록 설정한다.
notifications:
  email:
    recipients:
      - seung7642@gmail.com