spring.security.oauth2.client:
  registration:
    google:
      client-id: 구글클라이언트ID
      client-secret: 구글클라이언트시크릿
      scope: profile,email
    naver:
      client-id: 네이버클라이언트ID
      client-secret: 네이버클라이언트시크릿
      redirect-uri: {baseUrl}/{action}/oauth2/code/{registrationId}
      authorization-grant-type: authorization_code
      scope: name,email,profile_image
      client-name: Naver
  provider:
    naver:
      authorization-uri: https://nid.naver.com/oauth2.0/authorize
      token-uri: https://nid.naver.com/oauth2.0/token
      user-info-uri: https://openapi.naver.com/v1/nid/me
      user-name-attribute: response