# 로그 설정 ( 후에 slf4j를 사용해서 로그 찍을거임 )
logging.level:
  org.springframework: INFO
  com.practice: DEBUG

# Pebble 설정
pebble:
  enabled: true
  prefix: /templates/
  suffix: .html
  cache: false
  contentType: text/html
  encoding: UTF-8
  exposeRequestAttributes: false
  exposeSessionAttributes: false
  defaultLocale: ko_KR
  strictVariables: false

# DB 커넥션 정보
spring:
  datasource:
    hikari:
      driver-class: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/practice_board?allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
      username: pangtrue
      password: pangtrue1234!@#$
