# -------------------------------
# CORE PROPERTIES
# -------------------------------

# SPRING
spring:
  profiles.include: oauth, production-db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        ddl-auto: none
    show-sql: true
  session:
    store-type: jdbc